service: serverless-golang-crud

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:table/serverless-golang-crud"  

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  users:
    handler: bin/usersApi
    events:
      - httpApi:
          path: /users
          method: get
      - httpApi:
          path: /users
          method: post
      - httpApi:
          path: /users
          method: put
      - httpApi:
          path: /users
          method: delete

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: serverless-golang-crud